.TH myapp 1 "March 3, 2025" "1.0.0" "MyApp Manual"

.SH NAME
myapp \- A brief description of your app

.SH SYNOPSIS
.B myapp
[\fIOPTIONS\fR]

.SH DESCRIPTION
This section describes what your app does.

.SH OPTIONS
.TP
.B \-h, --help
Show help message.

.TP
.B \-v, --version
Print version information.

.SH EXAMPLES
Run the app normally:
.B myapp

.SH AUTHOR
Written by Your Name.

.SH SEE ALSO
.BR otherapp (1)
